server:
  port: 80
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 该配置打开表示可以和nacos进行结合,可以发现nacos上面的服务
    nacos:
      discovery:
        server-addr: 121.89.178.219:8848
  datasource:
    url: jdbc:mysql://121.89.178.219:3306/gateway?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
jwt:
  online-key: abcdefg